spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/MicroServiceAccounts
#    url: jdbc:postgresql://host.docker.internal:5432/MicroServiceAccounts   #for docker
#     username: postgres
#     password: root123
    url: jdbc:mysql://localhost:3306/accountsdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: create, create-drop, update, validate, none
    show-sql: true      # Set to false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Set to false in production
server:
 port: 8080
# Optional: Logging configuration for database queries
logging:
  level:
    org.hibernate.SQL: DEBUG           # Set to INFO or WARN in production
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Set to INFO in production
