spring:
  config:
    activate:
      on-profile: prod
build:
  version: 1.0.5
accounts:
  message: "Welcome to EazyBank accounts related production APIs "
  contactDetails:
    name: "Saqlen - Developer"
    email: "{cipher}54df4820c46109e01050d724803052bb7c26ffe081a6f75f7e29fc512f569cc19d09fe70bed09cf256dbfefad1a09de7"
  onCallSupport:
    - (555) 093-1234
    - (555) 389-1345
