spring:
  config:
    activate:
      on-profile: "qa"
build:
    version: 2.0.0
accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "Fahd - Developer"
    email: "fahd@eazybank.com"
  onCallSupport:
    - (555) 531-1234
    - (555) 029-1345