spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MicroServiceAccounts
#    url: jdbc:postgresql://host.docker.internal:5432/MicroServiceAccounts
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Options: create, create-drop, update, validate, none
    show-sql: true      # Set to false in production
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true  # Set to false in production
  config:
    import: 
      - application_qa.yml
      - application_prod.yml
  profiles:
    active:
    - prod
server:
 port: 8088
# Optional: Logging configuration for database queries
logging:
  level:
    org.hibernate.SQL: DEBUG           # Set to INFO or WARN in production
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Set to INFO in production